name: Dev pandora
on: [push]
jobs:
  I-AM-Myself:
    runs-on: ubuntu-latest
    steps:
      - name: Say my Code
        run: echo "The Awesome pandora Team"
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  Clone-My-Repository:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: List all the file
        run: Ls -larh
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: python-pandora
